### ISSUE TITLE
Error in TTS error description

### ISSUE THREAD

**Issue by danijel3** [huggingface/speech-to-speech#100]
The line is in a TTS class, but the error refers to STT:

https://github.com/huggingface/speech-to-speech/blob/d8afa799ac72c3411ab27846af4e0f50137a187f/TTS/parler_handler.py#L71

**Comment by eustlb** [comment]
Hey @danijel3, thanks for finding this typo! 
Fixed in [this commit](https://github.com/huggingface/speech-to-speech/commit/a3bc53b625dff73478fa8297dbd9d3abc3e2a1aa), added you as a co-author 😊
