### ISSUE TITLE
add python commandline args documentation  

### ISSUE THREAD

**Issue by shubham-samant** [huggingface/speech-to-speech#114]
---
## 1. **General Options**

These options apply broadly to the entire pipeline, affecting overall behavior and settings.

| **Argument**                                           | **Subcategory**             | **Description**                                                                                                                                                          | **Default**                                                                                                                                          |
|--------------------------------------------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| `-h`, `--help`                                         | **Help**                    | Show this help message and exit                                                                                                                                          | N/A                                                                                                                                                  |
| `--device DEVICE`                                      | **Device Configuration**    | Overrides the device for all handlers                                                                                                                                     | `None`                                                                                                                                               |
| `--mode MODE`                                          | **Mode Selection**          | Mode to run the pipeline in: `'local'` or `'socket'`                                                                                                                      | `socket`                                                                                                                                            |
| `--log_level LOG_LEVEL`                                | **Logging**                 | Logging level (e.g., `debug`, `info`, `warning`)                                                                                                                         | `info`                                                                                                                                               |
| `--language LANGUAGE`                                  | **Language Settings**       | Conversation language (`en`, `fr`, `es`, `zh`, `ko`, `ja`, `None`, `auto`)                                                                                              | `en`                                                                                                                                                |
| `--user_role USER_ROLE`                                | **Chat Roles**              | Role assigned to the user in the chat context                                                                                                                             | `user`                                                                                                                                               |
| `--init_chat_role INIT_CHAT_ROLE`                      | **Chat Roles**              | Initial role for setting up the chat context                                                                                                                              | `system`                                                                                                                                            |
| `--init_chat_prompt INIT_CHAT_PROMPT`                  | **Chat Initialization**     | Initial chat prompt to establish context for the language model                                                                                                           | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."               |
| `--chat_size CHAT_SIZE`                                | **Chat Settings**           | Number of assistant-user interactions to keep                                                                                                                             | `2`                                                                                                                                                  |
| `--local_mac_optimal_settings [LOCAL_MAC_OPTIMAL_SETTINGS]` | **Platform Optimization** | Sets optimal settings for Mac OS, enabling `whisper-mlx`, `MLX LM`, and `MeloTTS`                                                                                       | `False`                                                                                                                                               |

---

## 2. **Socket Configuration**

Settings related to socket connections for data transmission.

| **Argument**                     | **Subcategory**       | **Description**                                                                                                                                                      | **Default**    |
|----------------------------------|-----------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------|
| `--recv_host RECV_HOST`          | **Receiving**         | Host IP address for socket connection (binds to all if `0.0.0.0`)                                                                                                    | `localhost`    |
| `--recv_port RECV_PORT`          | **Receiving**         | Port number for the socket server                                                                                                                                 | `12345`        |
| `--send_host SEND_HOST`          | **Sending**           | Host IP address for sending socket connection                                                                                                                        | `localhost`    |
| `--send_port SEND_PORT`          | **Sending**           | Port number for sending socket server                                                                                                                                | `12346`        |
| `--chunk_size CHUNK_SIZE`        | **Data Transmission** | Size of data chunks over the socket (bytes)                                                                                                                            | `1024`         |

---

## 3. **Speech-to-Text (STT) Options**

Configurations for the Speech-to-Text component.

| **Argument**                                           | **Subcategory**           | **Description**                                                                                                             | **Default**                              |
|--------------------------------------------------------|---------------------------|-----------------------------------------------------------------------------------------------------------------------------|------------------------------------------|
| `--stt STT`                                            | **Engine Selection**     | Speech-to-Text engine: `'whisper'`, `'whisper-mlx'`, or `'paraformer'`                                                    | `whisper`                                |
| `--stt_model_name STT_MODEL_NAME`                      | **Model Configuration**  | Pretrained Whisper model                                                                                                   | `distil-whisper/distil-large-v3`         |
| `--stt_device STT_DEVICE`                              | **Device Configuration** | Device for STT model (`cuda`, `cpu`, etc.)                                                                                | `cuda`                                   |
| `--stt_torch_dtype STT_TORCH_DTYPE`                    | **Data Type**            | PyTorch data type for STT (`float32`, `float16`, `bfloat16`)                                                              | `float16`                                |
| `--stt_compile_mode STT_COMPILE_MODE`                  | **Compilation**          | Torch compile mode: `'default'`, `'reduce-overhead'`, `'max-autotune'`                                                    | `None`                                   |
| `--stt_gen_max_new_tokens STT_GEN_MAX_NEW_TOKENS`      | **Generation Parameters**| Max new tokens for STT generation                                                                                           | `128`                                    |
| `--stt_gen_num_beams STT_GEN_NUM_BEAMS`                | **Generation Parameters**| Number of beams for beam search in STT                                                                                      | `1`                                      |
| `--stt_gen_return_timestamps [STT_GEN_RETURN_TIMESTAMPS]` | **Output Configuration** | Return timestamps with transcriptions                                                                                      | `False`                                  |
| `--stt_gen_task STT_GEN_TASK`                          | **Task Specification**   | Task for STT (e.g., `'transcribe'`)                                                                                          | `transcribe`                             |
| `--paraformer_stt_model_name PARAFORMER_STT_MODEL_NAME` | **Engine Configuration** | Pretrained Paraformer model                                                                                                 | `paraformer-zh`                          |
| `--paraformer_stt_device PARAFORMER_STT_DEVICE`        | **Device Configuration** | Device for Paraformer STT model                                                                                              | `cuda`                                   |

---

## 4. **Language Model (LLM) Options**

Settings pertaining to the Language Model component.

| **Argument**                             | **Subcategory**           | **Description**                                                                                                    | **Default**                                |
|------------------------------------------|---------------------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------|
| `--llm LLM`                               | **Engine Selection**     | Language Model: `'transformers'` or `'mlx-lm'`                                                                    | `transformers`                             |
| `--lm_model_name LM_MODEL_NAME`           | **Model Configuration**  | Pretrained Language Model                                                                                           | `HuggingFaceTB/SmolLM-360M-Instruct`       |
| `--lm_device LM_DEVICE`                   | **Device Configuration** | Device for Language Model (`cuda`, `cpu`, etc.)                                                                    | `cuda`                                     |
| `--lm_torch_dtype LM_TORCH_DTYPE`         | **Data Type**            | PyTorch data type for LM (`float32`, `float16`, `bfloat16`)                                                        | `float16`                                  |
| `--lm_gen_max_new_tokens LM_GEN_MAX_NEW_TOKENS` | **Generation Parameters** | Max new tokens for LM generation                                                                                        | `128`                                       |
| `--lm_gen_min_new_tokens LM_GEN_MIN_NEW_TOKENS` | **Generation Parameters** | Min new tokens for LM generation                                                                                        | `0`                                         |
| `--lm_gen_temperature LM_GEN_TEMPERATURE`   | **Generation Parameters** | Randomness of LM output (0.0 for deterministic)                                                                    | `0.0`                                       |
| `--lm_gen_do_sample [LM_GEN_DO_SAMPLE]`     | **Generation Configuration** | Use sampling in LM generation                                                                                       | `False`                                     |

---

## 5. **Text-to-Speech (TTS) Options**

Configurations for the Text-to-Speech component.

| **Argument**                                           | **Subcategory**             | **Description**                                                                                                    | **Default**                                                                                                                                                           |
|--------------------------------------------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `--tts TTS`                                            | **Engine Selection**       | Text-to-Speech engine: `'parler'`, `'melo'`, or `'chatTTS'`                                                       | `parler`                                                                                                                                                              |
| `--tts_model_name TTS_MODEL_NAME`                      | **Model Configuration**    | Pretrained TTS model                                                                                                | `ylacombe/parler-tts-mini-jenny-30H`                                                                                                                                  |
| `--tts_device TTS_DEVICE`                              | **Device Configuration**   | Device for TTS model (`cuda`, `cpu`, etc.)                                                                        | `cuda`                                                                                                                                                                 |
| `--tts_torch_dtype TTS_TORCH_DTYPE`                    | **Data Type**              | PyTorch data type for TTS (`float32`, `float16`, `bfloat16`)                                                      | `float16`                                                                                                                                                              |
| `--tts_compile_mode TTS_COMPILE_MODE`                  | **Compilation**            | Torch compile mode for TTS: `'default'`, `'reduce-overhead'`, `'max-autotune'`                                   | `None`                                                                                                                                                                 |
| `--tts_gen_min_new_tokens TTS_GEN_MIN_NEW_TOKENS`      | **Generation Parameters**  | Min new tokens for TTS generation (~0.1 secs)                                                                     | `64`                                                                                                                                                                   |
| `--tts_gen_max_new_tokens TTS_GEN_MAX_NEW_TOKENS`      | **Generation Parameters**  | Max new tokens for TTS generation (~6 secs)                                                                         | `512`                                                                                                                                                                  |
| `--description DESCRIPTION`                            | **Voice Configuration**    | Description of speaker's voice and style for TTS                                                                     | "A female speaker with a slightly low-pitched voice delivers her words quite expressively, in a very confined sounding environment with clear audio quality. She speaks very fast." |
| `--play_steps_s PLAY_STEPS_S`                          | **Playback Settings**      | Time interval (seconds) for speech playback steps                                                                   | `1.0`                                                                                                                                                                  |
| `--chat_tts_stream [CHAT_TTS_STREAM]`                  | **Streaming Configuration** | Enable streaming mode for Chat TTS                                                                                   | `True`                                                                                                                                                                 |
| `--no_chat_tts_stream`                                 | **Streaming Configuration** | Disable streaming mode for Chat TTS                                                                                  | `False`                                                                                                                                                                |
| `--chat_tts_device CHAT_TTS_DEVICE`                    | **Device Configuration**   | Device for Chat TTS speech synthesis                                                                                  | `cuda`                                                                                                                                                                 |
| `--chat_tts_chunk_size CHAT_TTS_CHUNK_SIZE`            | **Data Transmission**      | Audio chunk size for Chat TTS processing (bytes)                                                                     | `512`                                                                                                                                                                  |

---

## 6. **OpenAPI Options**

Settings related to integrating with OpenAPI for language models.

| **Argument**                                           | **Subcategory**               | **Description**                                                                                                     | **Default**      |
|--------------------------------------------------------|-------------------------------|---------------------------------------------------------------------------------------------------------------------|------------------|
| `--open_api_model_name OPEN_API_MODEL_NAME`            | **Model Configuration**       | Pretrained OpenAPI Language Model                                                                                  | `deepseek-chat`  |
| `--open_api_user_role OPEN_API_USER_ROLE`              | **Chat Roles**                | User role in OpenAPI chat context                                                                                   | `user`           |
| `--open_api_init_chat_role OPEN_API_INIT_CHAT_ROLE`    | **Chat Roles**                | Initial role for OpenAPI chat                                                                                       | `system`         |
| `--open_api_init_chat_prompt OPEN_API_INIT_CHAT_PROMPT`| **Chat Initialization**       | Initial chat prompt for OpenAPI LM                                                                                   | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."               |
| `--open_api_chat_size OPEN_API_CHAT_SIZE`              | **Chat Settings**             | Number of OpenAPI chat interactions to keep                                                                          | `2`              |
| `--open_api_api_key OPEN_API_API_KEY`                  | **Authentication**            | API key for OpenAPI authentication                                                                                    | `None`           |
| `--open_api_base_url OPEN_API_BASE_URL`                | **Endpoint Configuration**    | Base URL for OpenAPI endpoints                                                                                       | `None`           |
| `--open_api_stream [OPEN_API_STREAM]`                  | **Streaming Configuration**   | Enable streaming for OpenAPI responses                                                                                | `False`          |

---

## 7. **MLX Language Model (MLX LM) Options**

Configurations for the MLX Language Model component.

| **Argument**                                           | **Subcategory**               | **Description**                                                                                                    | **Default**                                |
|--------------------------------------------------------|-------------------------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------|
| `--mlx_lm_model_name MLX_LM_MODEL_NAME`                | **Model Configuration**       | Pretrained MLX Language Model                                                                                      | `mlx-community/SmolLM-360M-Instruct`        |
| `--mlx_lm_device MLX_LM_DEVICE`                        | **Device Configuration**      | Device for MLX LM (`cuda`, `mps`, etc.)                                                                            | `mps`                                      |
| `--mlx_lm_torch_dtype MLX_LM_TORCH_DTYPE`              | **Data Type**                 | PyTorch data type for MLX LM (`float32`, `float16`, `bfloat16`)                                                    | `float16`                                  |
| `--mlx_lm_user_role MLX_LM_USER_ROLE`                  | **Chat Roles**                | User role in MLX LM chat context                                                                                   | `user`                                     |
| `--mlx_lm_init_chat_role MLX_LM_INIT_CHAT_ROLE`        | **Chat Roles**                | Initial role for MLX LM chat                                                                                       | `system`                                   |
| `--mlx_lm_init_chat_prompt MLX_LM_INIT_CHAT_PROMPT`    | **Chat Initialization**       | Initial chat prompt for MLX LM                                                                                       | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."               |
| `--mlx_lm_gen_max_new_tokens MLX_LM_GEN_MAX_NEW_TOKENS`| **Generation Parameters**     | Max new tokens for MLX LM generation                                                                                 | `128`                                      |
| `--mlx_lm_gen_temperature MLX_LM_GEN_TEMPERATURE`        | **Generation Parameters**     | Randomness of MLX LM output (0.0 for deterministic)                                                                   | `0.0`                                      |
| `--mlx_lm_gen_do_sample [MLX_LM_GEN_DO_SAMPLE]`        | **Generation Configuration**  | Use sampling in MLX LM generation                                                                                   | `False`                                   |
| `--mlx_lm_chat_size MLX_LM_CHAT_SIZE`                  | **Chat Settings**             | Number of MLX LM chat interactions to keep                                                                            | `2`                                        |

---

## 8. **MeloTTS Options**

Settings specific to the MeloTTS component for text synthesis.

| **Argument**                                   | **Subcategory**            | **Description**                                                    | **Default**    |
|------------------------------------------------|----------------------------|--------------------------------------------------------------------|----------------|
| `--melo_language MELO_LANGUAGE`               | **Language Settings**     | Language for text synthesis (`EN_NEWEST`, etc.)                    | `en`           |
| `--melo_device MELO_DEVICE`                    | **Device Configuration**  | Device for MeloTTS speech synthesis (`auto`, etc.)                  | `auto`         |
| `--melo_speaker_to_id MELO_SPEAKER_TO_ID`      | **Speaker Configuration** | Speaker name to ID mapping                                          | `['EN-Newest']` |

---

## 9. **Audio Settings**

Configurations related to audio processing and handling.

| **Argument**                             | **Subcategory**           | **Description**                                                                                                           | **Default** |
|------------------------------------------|---------------------------|---------------------------------------------------------------------------------------------------------------------------|-------------|
| `--sample_rate SAMPLE_RATE`               | **Audio Parameters**     | Audio sample rate in Hertz                                                                                                | `16000`     |
| `--min_silence_ms MIN_SILENCE_MS`         | **Speech Segmentation**  | Minimum silence duration for segmenting speech (ms)                                                                     | `250`       |
| `--min_speech_ms MIN_SPEECH_MS`           | **Speech Segmentation**  | Minimum valid speech segment duration (ms)                                                                                | `500`       |
| `--max_speech_ms MAX_SPEECH_MS`           | **Speech Segmentation**  | Maximum continuous speech duration before split                                                                             | `inf`       |
| `--speech_pad_ms SPEECH_PAD_MS`           | **Speech Padding**       | Padding added to speech segments (ms)                                                                                      | `500`       |
| `--audio_enhancement [AUDIO_ENHANCEMENT]`  | **Enhancement**          | Enables audio enhancement techniques (e.g., noise reduction, equalization, echo cancellation)                           | `False`     |
| `--max_prompt_pad_length MAX_PROMPT_PAD_LENGTH` | **Compilation Settings** | Max power of 2 for prompt padding during compilation                                                                    | `8`         |

---

### **Initial Chat Prompts**

Several arguments share a common purpose: setting the initial chat prompt to establish the AI assistant's context. Here's a unified view:

| **Argument**                                             | **Subcategory**         | **Description**                                                | **Default**                                                                                                                                                     |
|----------------------------------------------------------|-------------------------|----------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `--init_chat_prompt INIT_CHAT_PROMPT`                    | **Chat Initialization** | Initial chat prompt for general LLM context                    | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."                           |
| `--open_api_init_chat_prompt OPEN_API_INIT_CHAT_PROMPT`  | **Chat Initialization** | Initial chat prompt for OpenAPI LLM context                     | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."                           |
| `--mlx_lm_init_chat_prompt MLX_LM_INIT_CHAT_PROMPT`      | **Chat Initialization** | Initial chat prompt for MLX LM context                           | "You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words."                           |

### **Description for Speaker's Voice**

| **Argument**               | **Subcategory**         | **Description**                                     | **Default**                                                                                                                                                             |
|----------------------------|-------------------------|-----------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `--description DESCRIPTION` | **Voice Configuration** | Description of speaker's voice and style for TTS | "A female speaker with a slightly low-pitched voice delivers her words quite expressively, in a very confined sounding environment with clear audio quality. She speaks very fast." |

### **Boolean Flags**

Some arguments are optional boolean flags, indicated by square brackets. They can be enabled by including the flag or disabled by using a negation (if available).

- **Enabling a Flag**: Use `--argument` to set to `True`.
- **Disabling a Flag**: Use `--no-argument` to set to `False` (where applicable).

**Examples:**

| **Flag**                           | **Subcategory**               | **Description**                                      |
|------------------------------------|-------------------------------|------------------------------------------------------|
| `[LOCAL_MAC_OPTIMAL_SETTINGS]`     | **Platform Optimization**    | Enable optimal settings for Mac OS                   |
| `[AUDIO_ENHANCEMENT]`              | **Enhancement**              | Enable audio enhancement techniques                  |
| `[STT_GEN_RETURN_TIMESTAMPS]`      | **Output Configuration**     | Return timestamps with transcriptions                |
| `[LM_GEN_DO_SAMPLE]`               | **Generation Configuration** | Use sampling in LM generation                        |
| `[OPEN_API_STREAM]`                | **Streaming Configuration**  | Enable streaming for OpenAPI responses               |
| `[CHAT_TTS_STREAM]`                | **Streaming Configuration**  | Enable streaming mode for Chat TTS                   |
| `[MLX_LM_GEN_DO_SAMPLE]`            | **Generation Configuration** | Use sampling in MLX LM generation                    |

**Note**: Not all flags have a corresponding `--no-` option. For those that don't, the absence of the flag means the default value is used.

---

**Comment by eustlb** [comment]
Hey @shubham-samant,
I fear that such an addition to the README would make it over-bloated. Likewise, adding it in a separate CLI.md file would require maintenance to ensure it's correctly updated. I feel like simply using python s2s_pipeline.py -h already serves this purpose. In my opinion, the only advantage of what you are proposing is improved visibility by splitting arguments into sections, yet I feel like this more general view of the pipeline is already offered by the README.
What do you think?

**Comment by shubham-samant** [comment]
Sure @eustlb 
For me this served the purpose of understanding what all i can customise quickly, without cloning and checking all the mixed commandline args, i am doing a project in speech-to-speech and ability for a quick glance at features, helps me take some quick decisions!

for maintaining the updated docs, a simple CI/CD pipeline of s2s_pipeline would always automatically create this doc based on latest updates,

It just helps in this small way, nothing more :-)
