### ISSUE TITLE
[Bug] Client hangs on KeyboardInterrupt

### ISSUE THREAD

**Issue by 3manifold** [huggingface/speech-to-speech#122]
## Description 
Although `"Finished streaming."` is printed when `KeyboardInterrupt` exception is raised, this is not the case in practice. The client seems to hang and this happens because there is a blocking call in the client's receiver thread. The client only closes after one terminates the server. 

## Reproduce
Run locally:
1. `python3 s2s_pipeline.py --recv_host 0.0.0.0 --send_host 0.0.0.0 --device cpu`
2. `python3 listen_and_play.py`
3. One can send `SIGINT` to the client using `kill -2 CLIENT_PID`

Implementation as well as description of the fix can be found in pull request https://github.com/huggingface/speech-to-speech/pull/121 .

**Comment by andimarafioti** [comment]
Merged the PR, thank you!
