### ISSUE TITLE
Need to integrate it with a frontend and expose it to the internet

### ISSUE THREAD

**Issue by imPdhar** [huggingface/speech-to-speech#132]
Hey folks, love what you guys have done! The server and client methodology works well on my local but fails to be deployed onto an IP. I have tried using ngrok, tried using FastAPI but nothing works. I thought by setting the right host-receiver IPs and ports would work directly by using the --recv_host --send_host but somehow it didn't respond. I just need a basic frontend and then expose it but in vain with that too. I am not sure what I am missing so it would be great if I received some quick help.

OS: Windows 11

**Comment by andimarafioti** [comment]
Hi 👋 We wrote a blog about this: https://huggingface.co/blog/s2s_endpoint

**Comment by imPdhar** [comment]
I need to use my own GPU so Inference Endpoints are a no-go. :( Is there a webclient code I can use if I want to run the server and communicate with it through the browser?

**Comment by imPdhar** [comment]
> For the frontend example about speech-to-speech interactions, maybe you can refer to our released [CleanS2S](https://github.com/opendilab/CleanS2S).
> 
> > Hey folks, love what you guys have done! The server and client methodology works well on my local but fails to be deployed onto an IP. I have tried using ngrok, tried using FastAPI but nothing works. I thought by setting the right host-receiver IPs and ports would work directly by using the --recv_host --send_host but somehow it didn't respond. I just need a basic frontend and then expose it but in vain with that too. I am not sure what I am missing so it would be great if I received some quick help.
> > OS: Windows 11
> 
> For the frontend example about speech-to-speech interactions, maybe you can refer to our released [CleanS2S](https://github.com/opendilab/CleanS2S).

Cool implementation but does it support custom huggingface models?

**Comment by PaParaZz1** [comment]
Of course, you can indicate the arbitrary huggingface LLM [here](https://github.com/opendilab/CleanS2S/blob/main/backend/s2s_server_pipeline.py#L944)

**Comment by imPdhar** [comment]
> Of course, you can indicate the arbitrary huggingface LLM [here](https://github.com/opendilab/CleanS2S/blob/main/backend/s2s_server_pipeline.py#L944)

I have some more questions so I will be raising an issue at your repo and then I'll ask relevant questions over there to avoid spam to this repo, hope that is fine

**Comment by andimarafioti** [comment]
So cool that the guys at CleanS2S managed to get this to work well already! They thank this project in the acknowledgments :)
