### ISSUE TITLE
MPS Error on Mac. I have downlaoded it manually and stillg getting the error

### ISSUE THREAD

**Issue by mitkox** [huggingface/speech-to-speech#21]
.s2s) mitko@mitko-3 speech-to-speech % python s2s_pipeline.py --recv_host localhost --send_host localhost --device mps
Flash attention 2 is not installed
Traceback (most recent call last):
  File "/Users/mitko/dev/speech-to-speech/s2s_pipeline.py", line 42, in <module>
    nltk.data.find('tokenizers/punkt_tab')
  File "/Users/mitko/dev/speech-to-speech/.s2s/lib/python3.12/site-packages/nltk/data.py", line 537, in find
    return FileSystemPathPointer(p)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mitko/dev/speech-to-speech/.s2s/lib/python3.12/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mitko/dev/speech-to-speech/.s2s/lib/python3.12/site-packages/nltk/data.py", line 312, in __init__
    raise OSError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/Users/mitko/nltk_data/tokenizers/punkt/PY3_tab'

**Comment by RonanKMcGovern** [comment]
that error is fixed by running this after installs: 
```
pip install git+https://github.com/nltk/nltk.git@3.8.2

```

**Comment by mitkox** [comment]
Did it. Now I am getting this error: python s2s_pipeline.py --mode local --device mps      
/Users/mitko/dev/speech-to-speech/.s2s/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/mitko/dev/speech-to-speech/s2s_pipeline.py", line 22, in <module>
    from transformers import (
ImportError: cannot import name 'TextIteratorStreamer' from 'transformers' (/Users/mitko/dev/speech-to-speech/.s2s/lib/python3.10/site-packages/transformers/__init__.py)

**Comment by RonanKMcGovern** [comment]
Yeah you need to update transformers:
```
git clone https://github.com/eustlb/speech-to-speech.git
cd speech-to-speech
git fetch --all
git checkout add-mps-support
python -m venv mpsEnv 
source mpsEnv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install --upgrade transformers
pip install git+https://github.com/nltk/nltk.git@3.8.2
git clone https://github.com/myshell-ai/MeloTTS.git
cd MeloTTS
pip install -e .
python -m unidic download
cd ../
python s2s_pipeline.py --mode local --device mps
```

It may also be best to best to close here and just track the PR where the mps branch was added: https://github.com/huggingface/speech-to-speech/pull/20

**Comment by andimarafioti** [comment]
yep sorry, I will improve the install process, it's not very clean with Melo
