### ISSUE TITLE
Error installing requirements: Could not find a version that satisfies the requirement nltk==3.8.2

### ISSUE THREAD

**Issue by RodriMora** [huggingface/speech-to-speech#3]
Hi!

When trying to install the requirements in a python venv, I got the following error:

```
ERROR: Could not find a version that satisfies the requirement nltk==3.8.2 (from versions: 2.0b8.macosx-10.5-i386, 2.0.1rc1.macosx-10.6-x86_64, 2.0.1rc2-git, 2.0b4, 2.0b5, 2.0b6, 2.0b7, 2.0b8, 2.0b9, 2.0.1rc1, 2.0.1rc3, 2.0.1rc4, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 3.0.0b1, 3.0.0b2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5b1, 3.5, 3.6, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.6.7, 3.7, 3.8, 3.8.1)
ERROR: No matching distribution found for nltk==3.8.2
```

Seems like the latest version in pip is 3.8.1:

https://pypi.org/project/nltk/ 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/2690aeb8-6fbd-43de-9dc6-47cf6374913c">

**Comment by ChristianWeyer** [comment]
I am running on a MBP M3 Max, and get the same error @eustlb:

```
❯ pip install -r requirements.txt
Collecting parler_tts@ git+https://github.com/huggingface/parler-tts.git (from -r requirements.txt (line 2))
  Cloning https://github.com/huggingface/parler-tts.git to /private/var/folders/5l/mksr7zj10lgb4y62_h1x1nxc0000gn/T/pip-install-2_1kw68_/parler-tts_6761ec10612a4caea539d0beb8203b7f
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/parler-tts.git /private/var/folders/5l/mksr7zj10lgb4y62_h1x1nxc0000gn/T/pip-install-2_1kw68_/parler-tts_6761ec10612a4caea539d0beb8203b7f
  Resolved https://github.com/huggingface/parler-tts.git to commit 9f34c1b8730efc9ed0337d96fd89e2ee6f1735b0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Ignored the following yanked versions: 3.6.4
ERROR: Could not find a version that satisfies the requirement nltk==3.8.2 (from versions: 2.0b4, 2.0b5, 2.0b6, 2.0b7, 2.0b8, 2.0b9, 2.0.1rc1, 2.0.1rc3, 2.0.1rc4, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 3.0.0b1, 3.0.0b2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5b1, 3.5, 3.6, 3.6.1, 3.6.2, 3.6.3, 3.6.5, 3.6.6, 3.6.7, 3.7, 3.8, 3.8.1)
ERROR: No matching distribution found for nltk==3.8.2
```

**Comment by RodriMora** [comment]
Manually changing the requirement to 3.8.1 will install it. But it has other problems down the line when launching:

```
OSError: No such file or directory: '/home/ubuntuai/nltk_data/tokenizers/punkt/PY3_tab'
```
I had to manually install nltk_data using:

```
python -m nltk.downloader all
```

but it doesn't create the ~/nltk_data/tokenizers/punkt/PY3_tab either, but manually renaming it works.
`cp -R ~/nltk_data/tokenizers/punkt/PY3 ~/nltk_data/tokenizers/punkt/PY3_tab`

Using a CUDA machine as a server it also needs to install wheels and flash attention:
(I'm using a python env)
`python -m pip install wheel`
`python -m pip install flash-attn --no-build-isolation`

And a mac as a client it needs sounddevice, so:
`python -m pip install sounddevice`

Now it sorta works, but after a couple of short questions it crashes: 

```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```
Running it on a 2x3090 system as a server, it's taking 19/24GB of VRAM in one card, loading the bf16 llama3.1 8B model

Note: if loading a quantized model like GPTQ you will probably also need:
`python -m pip install optimum`

**Comment by gvijqb** [comment]
Try this:
```
pip install git+https://github.com/nltk/nltk.git@3.8.2
```

As mentioned here:
https://github.com/nltk/nltk/issues/3301#issuecomment-2291304097

**Comment by CeKMTL** [comment]
Is this supposed to work on CUDA only or can be used on M series Mac?

**Comment by RonanKMcGovern** [comment]
I was able to run with:
```
git clone https://github.com/eustlb/speech-to-speech
cd speech-to-speech
sed -i '/nltk/s/==.*$//' requirements.txt
sed -i 's/tokenizer\/punkt_tab/tokenizer\/punkt/' s2s_pipeline.py
```

Basically install the latest nltk and update that line to punkt not punkt_tab

**Comment by jikkuatwork** [comment]
I modified the requirements to not specify any version and it worked:

```
nltk
parler_tts @ git+https://github.com/huggingface/parler-tts.git
torch==2.4.0
```

**Comment by andimarafioti** [comment]
This should be fixed now! please reopen if it still fails, but we changed the nltk version a few times already since.
And it should work with mac as well on main now!

**Comment by sysrams** [comment]
pip install git+https://github.com/nltk/nltk.git@3.8.2
Looking in indexes: https://aws:****@abcexample-554406110632.d.codeartifact.us-east-1.amazonaws.com/pypi/repo2/simple/
Collecting git+https://github.com/nltk/nltk.git@3.8.2
  Cloning https://github.com/nltk/nltk.git (to revision 3.8.2) to /private/var/folders/bs/p_08j6x54hqc718gw6rc4y140000gn/T/pip-req-build-_nf82_9x
  Running command git clone --filter=blob:none --quiet https://github.com/nltk/nltk.git /private/var/folders/bs/p_08j6x54hqc718gw6rc4y140000gn/T/pip-req-build-_nf82_9x
  Running command git checkout -q 36efb109f093df489a572053dfd4e01a0b8bf015
  Resolved https://github.com/nltk/nltk.git to commit 36efb109f093df489a572053dfd4e01a0b8bf015
  Preparing metadata (setup.py) ... done
WARNING: 401 Error, Credentials not correct for https://abcexample-554406110632.d.codeartifact.us-east-1.amazonaws.com/pypi/repo2/simple/click/
INFO: pip is looking at multiple versions of nltk to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement click (from nltk) (from versions: none)
WARNING: 401 Error, Credentials not correct for https://abcexample-554406110632.d.codeartifact.us-east-1.amazonaws.com/pypi/repo2/simple/pip/
ERROR: No matching distribution found for click
