### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 6) and -r requirements.txt (line 7) because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by JunZhan2000** [huggingface/speech-to-speech#34]
error while pip install -r requirements.txt:

The conflict is caused by:
    lightning-whisper-mlx 0.0.10 depends on mlx
    mlx-lm 0.17.0 depends on mlx>=0.14.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by andimarafioti** [comment]
Weird, this https://github.com/huggingface/speech-to-speech/issues/33 says that they run `pip install` fine. In any case, I pushed a change to main just now relaxing the mlx-lm requirement. Does it run for you @JunZhan2000 ?

**Comment by andimarafioti** [comment]
changed the readme to suggest using `uv`, it is better anyway :)

**Comment by RodriMora** [comment]
mlx won't install in a non-mac server as there is no build for linux:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/2f0dc1bc-fde4-4fb5-96fd-66fcafb10c19">

Having problems too

**Comment by andimarafioti** [comment]
ok that makes more sense. I can push a quick fix

**Comment by andimarafioti** [comment]
This should do it for linux users: https://github.com/huggingface/speech-to-speech/commit/cb48b916cf15b0805a6460862c7141dac33e41eb
And for mac users we have a requirements_mac.txt
Tomorrow I'll do a cleaner implementation per platform, but right now I wanted to push a hot fix

**Comment by RodriMora** [comment]
> This should do it for linux users: [cb48b91](https://github.com/huggingface/speech-to-speech/commit/cb48b916cf15b0805a6460862c7141dac33e41eb) And for mac users we have a requirements_mac.txt Tomorrow I'll do a cleaner implementation per platform, but right now I wanted to push a hot fix

I can confirm this fixes the issue, tested on both mac and linux+nvidia

I think there should be a note in the readme for Nvidia's system to also install flash attention:
```
pip install wheel
pip install flash-attn --no-build-isolation
```

**Comment by andimarafioti** [comment]
I agree, do you want to make the change to the readme and make a PR or should I?

**Comment by RodriMora** [comment]
> I agree, do you want to make the change to the readme and make a PR or should I?

please do it how you feel it would be more clear

**Comment by andimarafioti** [comment]
Added the warning 👍
