### ISSUE TITLE
No more server+client support?

### ISSUE THREAD

**Issue by RodriMora** [huggingface/speech-to-speech#36]
I've seen that the docs for running the client in another server have been removed:
https://github.com/huggingface/speech-to-speech/commit/dc926fce74c0f46399b879111d02f15af7020af6

but the listen_and_play.py is still there.

Is there support for server+client planned? of everything should be local.

Many powerfull GPU systems are run headless so being able to use the cliente in another server would be great.

**Comment by andimarafioti** [comment]
oh no, what I removed is that the `local` version uses a server with localhost. You can still run this with a server. But now If you run locally, instead of spawning a connection to itself, it just runs everything locally... I hope that makes sense.

**Comment by RodriMora** [comment]
So for server + remote client the commands are still:

Server:
`python s2s_pipeline.py --recv_host 0.0.0.0 --send_host 0.0.0.0`

Client:
`python listen_and_play.py --host <IP address of your server>`

Maybe it's useful to add it back to the docs? Right now there is not information on how to run the `python listen_and_play.py `

**Comment by andimarafioti** [comment]
I added it back to the docs 😅  You were right, the docs were confusing
