### ISSUE TITLE
Changing the whisper code faster-whisper

### ISSUE THREAD

**Issue by wajihullahbaig** [huggingface/speech-to-speech#4]
If we want to change the backed to use a library like faster-whisper, will this be possible ?

**Comment by Diger2010** [comment]
https://coins.game/c/1262336_f8d106ac

**Comment by andimarafioti** [comment]
This is definitely possible! Our idea with this library is to make it modular. Would you like to work on that? You can check on my mps support PR how I adapted the code to a new whisper class. Otherwise I can also do it, but it seems like an easy project ;)

**Comment by wajihullahbaig** [comment]
> This is definitely possible! Our idea with this library is to make it modular. Would you like to work on that? You can check on my mps support PR how I adapted the code to a new whisper class. Otherwise I can also do it, but it seems like an easy project ;)

Well.let see then how  I can do this

**Comment by Diger2010** [comment]
diger0809@gmail.com

**Comment by andimarafioti** [comment]
This is now added to the main branch!
