### ISSUE TITLE
Code Related Question

### ISSUE THREAD

**Issue by mr-shitij** [huggingface/speech-to-speech#45]
I was going through code and i am not able to find 

from mlx_lm import load, stream_generate, generate

where are these functions comming from `load, stream_generate, generate`

Thanks.

**Comment by andimarafioti** [comment]
mlx-lm is a library. It's installed as one of the 'mac' dependencies. You can find the code here: https://github.com/ml-explore/mlx-examples/tree/main/llms/mlx_lm

**Comment by mr-shitij** [comment]
Then why it is not included in requirements.txt; i found it in requirements_mac.txt

**Comment by mr-shitij** [comment]
ok got it; Thanks
