### ISSUE TITLE
Assignment of max_new_tokens to min_new_tokens

### ISSUE THREAD

**Issue by mr-shitij** [huggingface/speech-to-speech#46]
I was going through code and found that we have specified max_new_tokens as min_new_tokens.
'''
            warmup_gen_kwargs = {
                "min_new_tokens": self.gen_kwargs["max_new_tokens"],
                "max_new_tokens": self.gen_kwargs["max_new_tokens"],
                **self.gen_kwargs,
            }
'''
It should need to get added in the arg parser as well.

can i go for it and raise the PR please ..!!

**Comment by mr-shitij** [comment]
I found this in LanguageModelHandler and WhisperSTTHandler class

**Comment by andimarafioti** [comment]
Thank you for raising this! I fixed it
