### ISSUE TITLE
Installing dependencies breaks because of nltk

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/speech-to-speech#6]
I tried running `pip install -r requirements.txt` and got the following error

```
ERROR: Ignored the following yanked versions: 3.6.4
ERROR: Could not find a version that satisfies the requirement nltk==3.8.2 (from versions: 2.0b4, 2.0b5, 2.0b6, 2.0b7, 2.0b8, 2.0b9, 2.0.1rc1, 2.0.1rc3, 2.0.1rc4, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 3.0.0b1, 3.0.0b2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5b1, 3.5, 3.6, 3.6.1, 3.6.2, 3.6.3, 3.6.5, 3.6.6, 3.6.7, 3.7, 3.8, 3.8.1)
ERROR: No matching distribution found for nltk==3.8.2
```

It appears that nltk removed version `3.8.2` from PyPI, would it be possible to change the version used in the dependencies for this project? See issue: https://github.com/nltk/nltk/issues/3301

**Comment by gvijqb** [comment]
Try this as a fix for now:
```
pip install git+https://github.com/nltk/nltk.git@3.8.2
```

As suggested here:
https://github.com/nltk/nltk/issues/3301#issuecomment-2291304097

**Comment by nsarrazin** [comment]
Yep this works great! 

I was missing a few other deps on Linux to run the client. Had to `pip install sounddevice` and also `apt install libportaudio2` not sure if that's helpful to others but sharing just in case. :smile:

**Comment by andimarafioti** [comment]
I fixed this, thanks for raising it!
