### ISSUE TITLE
Can support llm by api? 

### ISSUE THREAD

**Issue by skytodmoon** [huggingface/speech-to-speech#65]
Greate project, we want use this in our production dev. And use dify chat api as below:
`http://192.168.32.241:8088/`
`Request POST /chat-messages
curl -X POST 'http://192.168.32.241:8088/v1/chat-messages' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "What are the specs of the iPhone 13 Pro Max?",
    "response_mode": "streaming",
    "conversation_id": "",
    "user": "abc-123",
    "files": [
      {
        "type": "image",
        "transfer_method": "remote_url",
        "url": "https://cloud.dify.ai/logo/logo-site.png"
      }
    ]
}'`
Cant this be supported?

**Comment by SinlinLi** [comment]
Strongly support. If the standard OpenAI API is supported, it will facilitate our use of large-parameter language models. This would be extremely convenient.

**Comment by andimarafioti** [comment]
I like this idea as well 💡It would probably add delay though, but it would be a good way to help people get this into prod. 

I will add it to the ideas. If you want to work on it, we welcome contributions :)

**Comment by jpysh** [comment]
current blocker for me. thank you.

**Comment by rchan26** [comment]
I'm happy to have a go at including OpenAI API support 😊

**Comment by rchan26** [comment]
ah, just seen there's already a PR for this in #81

**Comment by MattiPaivike** [comment]
Bump, this would be perfect addition!

**Comment by eustlb** [comment]
Hey there, the OpenAI API PR (https://github.com/huggingface/speech-to-speech/pull/81) is now merged!
Give ti a go simply adding the following parameters: `--llm open_api --open_api_api_key YOUR_API_KEY --open_api_init_chat_prompt "You are an helpfull AI assistant" --open_api_stream True --open_api_model_name gpt-3.5-turbo`
