### ISSUE TITLE
[Documentation] Add unidoc download step to running

### ISSUE THREAD

**Issue by iamnotagentleman** [huggingface/speech-to-speech#76]
When i tried to run `python s2s_pipeline.py --local_mac_optimal_settings` I encountered an error related to the UniDic library

Error Response;

`------------------- ERROR DETAILS ------------------------
arguments: 
default dictionary path: /Users/veli/xxxx/yyyy/venv/lib/python3.10/site-packages/unidic/dicdir
[ifs] no such file or directory: /Users/veli/xxxx/yyyy/venv/lib/python3.10/site-packages/unidic/dicdir/mecabrc
----------------------------------------------------------
`

you need to initialize MeCab by downloading the necessary UniDic dictionary files. This can be done by running the following command:

`python -m unidic download`

**Comment by andimarafioti** [comment]
There we go, thank you for raising this 👍
