### ISSUE TITLE
LightningWhisperSTTHandler.setup() got an unexpected keyword argument 'language'

### ISSUE THREAD

**Issue by rchan26** [huggingface/speech-to-speech#83]
Error comes from running `python s2s_pipeline.py --local_mac_optimal_settings --device mps`. This is due to `LightningWhisperSTTHandler` not having a `language` arg.

Will make a PR for a quick fix.

**Comment by andimarafioti** [comment]
Thank you for taking care of this :)

**Comment by Kong4Git** [comment]
Thank you very much，it work
