### ISSUE TITLE
请问macOS的multi-language还在开发吗？

### ISSUE THREAD

**Issue by ybm911** [huggingface/speech-to-speech#88]
我看了下源码，macOS的lightning_whisper_mlx_handler.py文件中没有添加多语言的支持功能。
I looked at the source code and found that the lightning_whisper_mlx_handler.py file of macOS does not have multi-language support.

![09a12ae95fbad23e387ace2d3e0a152e348507042](https://github.com/user-attachments/assets/2f646ad3-e0bd-4695-9a97-4c592b98d5e6)

**Comment by andimarafioti** [comment]
That is accurate. We will work on the feature parity for mac soon.

**Comment by ybm911** [comment]
Hello, dear developer, I submitted a PR that can support multi-language functions on macOS. I wonder if you can take a look: 
https://github.com/huggingface/speech-to-speech/pull/93#issue-2512024377
