### ISSUE TITLE
error: no module named "df"

### ISSUE THREAD

**Issue by insufficient-will** [huggingface/speech-to-speech#89]
**input**
python s2s_pipeline.py  --device mps --lm_model_name meta-llama/Meta-Llama-3.1-8B-Instruct --init_chat_role system --tts melo --stt_model_name openai/whisper-large-v3 --language zh --mode local

**output**
Traceback (most recent call last):
  File "/Users/lutian/speech-to-speech/s2s_pipeline.py", line 10, in <module>
    from VAD.vad_handler import VADHandler
  File "/Users/lutian/speech-to-speech/VAD/vad_handler.py", line 9, in <module>
    from df.enhance import enhance, init_df
ModuleNotFoundError: No module named 'df'

**checked vad_handler.py**
line 9: from df.enhance import enhance, init_df

**Comment by rs545837** [comment]
I think that deep filternet did not get installed in your environement, could you try and check using?
```bash
pip show deepfilternet
```

**Comment by andimarafioti** [comment]
It's a new dependency from a recent PR. You just need to install the requirements again

**Comment by insufficient-will** [comment]
I re-installed everything and the problem was solved. Thanks.
I git pulled and didn't re-run the pip install the first time.

**Comment by rs545837** [comment]
Great!
